spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: raspberry
    url: jdbc:mysql://192.168.31.138:3306/quickapi?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

constant:
  chromePath: C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
  bmobAppId: 86855067edf9cf9d0132c02f2f7aed6e
  bmobAppKey: 42779deb594bad1d40bf134c5a91dc6c